source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'thin'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sprockets'
gem 'coffee-script'
gem 'ruby-taglib2'
gem 'sinatra-flash'
