require_relative 'models/sluggable'
require_relative 'models/growl_notification'
require_relative 'models/artist'
require_relative 'models/album'
require_relative 'models/song'
require_relative 'models/importer'
